export interface VietnamBank {
  bin: string;
  code: string;
  shortName: string;
  name: string;
  logo: string;
}

export const VIETNAM_BANKS: VietnamBank[] = [
  {
    bin: '970415',
    code: 'ICB',
    shortName: 'VietinBank',
    name: 'Ngân hàng TMCP Công thương Việt Nam',
    logo: 'https://cdn.vietqr.io/img/ICB.png',
  },
  {
    bin: '970436',
    code: 'VCB',
    shortName: 'Vietcombank',
    name: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
    logo: 'https://cdn.vietqr.io/img/VCB.png',
  },
  {
    bin: '970422',
    code: 'MB',
    shortName: 'MBBank',
    name: 'Ngân hàng TMCP Quân đội',
    logo: 'https://cdn.vietqr.io/img/MB.png',
  },
  {
    bin: '970407',
    code: 'TCB',
    shortName: 'Techcombank',
    name: 'Ngân hàng TMCP Kỹ thương Việt Nam',
    logo: 'https://cdn.vietqr.io/img/TCB.png',
  },
  {
    bin: '970416',
    code: 'ACB',
    shortName: 'ACB',
    name: 'Ngân hàng TMCP Á Châu',
    logo: 'https://cdn.vietqr.io/img/ACB.png',
  },
  {
    bin: '970418',
    code: 'BIDV',
    shortName: 'BIDV',
    name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    logo: 'https://cdn.vietqr.io/img/BIDV.png',
  },
  {
    bin: '970432',
    code: 'VPB',
    shortName: 'VPBank',
    name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    logo: 'https://cdn.vietqr.io/img/VPB.png',
  },
  {
    bin: '970423',
    code: 'TPB',
    shortName: 'TPBank',
    name: 'Ngân hàng TMCP Tiên Phong',
    logo: 'https://cdn.vietqr.io/img/TPB.png',
  },
  {
    bin: '970403',
    code: 'STB',
    shortName: 'Sacombank',
    name: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    logo: 'https://cdn.vietqr.io/img/STB.png',
  },
  {
    bin: '970437',
    code: 'HDB',
    shortName: 'HDBank',
    name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh',
    logo: 'https://cdn.vietqr.io/img/HDB.png',
  },
  {
    bin: '970441',
    code: 'VIB',
    shortName: 'VIB',
    name: 'Ngân hàng TMCP Quốc tế Việt Nam',
    logo: 'https://cdn.vietqr.io/img/VIB.png',
  },
  {
    bin: '970443',
    code: 'SHB',
    shortName: 'SHB',
    name: 'Ngân hàng TMCP Sài Gòn - Hà Nội',
    logo: 'https://cdn.vietqr.io/img/SHB.png',
  },
  {
    bin: '970448',
    code: 'OCB',
    shortName: 'OCB',
    name: 'Ngân hàng TMCP Phương Đông',
    logo: 'https://cdn.vietqr.io/img/OCB.png',
  },
  {
    bin: '970426',
    code: 'MSB',
    shortName: 'MSB',
    name: 'Ngân hàng TMCP Hàng Hải Việt Nam',
    logo: 'https://cdn.vietqr.io/img/MSB.png',
  },
  {
    bin: '970405',
    code: 'VBA',
    shortName: 'Agribank',
    name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    logo: 'https://cdn.vietqr.io/img/VBA.png',
  },
  {
    bin: '970431',
    code: 'EIB',
    shortName: 'Eximbank',
    name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam',
    logo: 'https://cdn.vietqr.io/img/EIB.png',
  },
  {
    bin: '970440',
    code: 'SEAB',
    shortName: 'SeABank',
    name: 'Ngân hàng TMCP Đông Nam Á',
    logo: 'https://cdn.vietqr.io/img/SEAB.png',
  },
  {
    bin: '970449',
    code: 'LPB',
    shortName: 'LPBank',
    name: 'Ngân hàng TMCP Lộc Phát Việt Nam',
    logo: 'https://cdn.vietqr.io/img/LPB.png',
  },
  {
    bin: '970428',
    code: 'NAB',
    shortName: 'NamABank',
    name: 'Ngân hàng TMCP Nam Á',
    logo: 'https://cdn.vietqr.io/img/NAB.png',
  },
  {
    bin: '970409',
    code: 'BAB',
    shortName: 'BacABank',
    name: 'Ngân hàng TMCP Bắc Á',
    logo: 'https://cdn.vietqr.io/img/BAB.png',
  },
  {
    bin: '970412',
    code: 'PVCB',
    shortName: 'PVcomBank',
    name: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    logo: 'https://cdn.vietqr.io/img/PVCB.png',
  },
  {
    bin: '970419',
    code: 'NVB',
    shortName: 'NCB',
    name: 'Ngân hàng TMCP Quốc Dân',
    logo: 'https://cdn.vietqr.io/img/NCB.png',
  },
  {
    bin: '970452',
    code: 'KLB',
    shortName: 'KienLongBank',
    name: 'Ngân hàng TMCP Kiên Long',
    logo: 'https://cdn.vietqr.io/img/KLB.png',
  },
  {
    bin: '970454',
    code: 'VCCB',
    shortName: 'VietCapitalBank',
    name: 'Ngân hàng TMCP Bản Việt',
    logo: 'https://cdn.vietqr.io/img/VCCB.png',
  },
  {
    bin: '970425',
    code: 'ABB',
    shortName: 'ABBANK',
    name: 'Ngân hàng TMCP An Bình',
    logo: 'https://cdn.vietqr.io/img/ABB.png',
  },
  {
    bin: '970438',
    code: 'BVB',
    shortName: 'BaoVietBank',
    name: 'Ngân hàng TMCP Bảo Việt',
    logo: 'https://cdn.vietqr.io/img/BVB.png',
  },
  {
    bin: '970427',
    code: 'VAB',
    shortName: 'VietABank',
    name: 'Ngân hàng TMCP Việt Á',
    logo: 'https://cdn.vietqr.io/img/VAB.png',
  },
  {
    bin: '970430',
    code: 'PGB',
    shortName: 'PGBank',
    name: 'Ngân hàng TMCP Thịnh vượng và Phát triển',
    logo: 'https://cdn.vietqr.io/img/PGB.png',
  },
  {
    bin: '970433',
    code: 'VIETBANK',
    shortName: 'VietBank',
    name: 'Ngân hàng TMCP Việt Nam Thương Tín',
    logo: 'https://cdn.vietqr.io/img/VIETBANK.png',
  },
  {
    bin: '970400',
    code: 'SGICB',
    shortName: 'SaigonBank',
    name: 'Ngân hàng TMCP Sài Gòn Công Thương',
    logo: 'https://cdn.vietqr.io/img/SGICB.png',
  },
  {
    bin: '970424',
    code: 'SHBVN',
    shortName: 'ShinhanBank',
    name: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
    logo: 'https://cdn.vietqr.io/img/SHBVN.png',
  },
  {
    bin: '963388',
    code: 'TIMO',
    shortName: 'Timo',
    name: 'Ngân hàng số Timo by Ban Viet Bank',
    logo: 'https://vietqr.net/portal-service/resources/icons/TIMO.png',
  },
  {
    bin: '546034',
    code: 'CAKE',
    shortName: 'CAKE',
    name: 'Ngân hàng số CAKE by VPBank',
    logo: 'https://cdn.vietqr.io/img/CAKE.png',
  },
];
