export enum CopilotSuggestionType {
  REPLY_DRAFT = 'REPLY_DRAFT',
  NEXT_BEST_ACTION = 'NEXT_BEST_ACTION',
  BATTLECARD = 'BATTLECARD',
}

export enum SuggestionStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DISMISSED = 'DISMISSED',
  APPLIED = 'APPLIED',
  EXPIRED = 'EXPIRED',
}

export enum CopilotActionType {
  REPLY_INSERT = 'REPLY_INSERT',
  SCHEDULE_DEMO = 'SCHEDULE_DEMO',
  CONVERT_TO_OPPORTUNITY = 'CONVERT_TO_OPPORTUNITY',
  SEND_PRICING = 'SEND_PRICING',
  DISMISS = 'DISMISS',
}

export enum DismissalReason {
  NOT_RELEVANT = 'NOT_RELEVANT',
  INCORRECT_INFORMATION = 'INCORRECT_INFORMATION',
  TOO_FORMAL = 'TOO_FORMAL',
  TOO_CASUAL = 'TOO_CASUAL',
  ALREADY_ADDRESSED = 'ALREADY_ADDRESSED',
  OTHER = 'OTHER',
}

export const COPILOT_SUGGESTIONS_QUEUE = 'copilot-suggestions';
export const GENERATE_COPILOT_SUGGESTIONS_JOB = 'generate-copilot-suggestions';
