/**
 * Initialization options passed to window.SalesCopilotWidget.init()
 */
export interface WidgetInitConfig {
  /**
   * The unique Web Chat channel website/widget token.
   */
  websiteToken: string;

  /**
   * Base URL of the Sales Copilot backend API (e.g. 'https://api.example.com').
   * Defaults to window.location.origin if omitted.
   */
  baseUrl?: string;

  /**
   * Placement on the screen: 'right' (default) or 'left'.
   */
  position?: 'right' | 'left';

  /**
   * Hide the floating chat launcher bubble (if triggering widget via custom button).
   */
  hideMessageBubble?: boolean;

  /**
   * Locale code for date and UI strings (default: 'en').
   */
  locale?: string;

  /**
   * Whether to require visitor to fill out pre-chat form before chatting.
   */
  preChatForm?: boolean;

  /**
   * Pre-identified user details (e.g. logged-in customer).
   */
  user?: Partial<UserIdentity>;

  /**
   * Callback fired when widget configuration and visitor session are ready.
   */
  onReady?: () => void;

  /**
   * Callback fired when a new message is received from an agent.
   */
  onMessage?: (message: WidgetMessage) => void;
}

/**
 * Logged-in user identification payload passed to setUser().
 */
export interface UserIdentity {
  /**
   * Unique user identifier in host system.
   */
  identifier: string;

  /**
   * Full name of the user.
   */
  name?: string;

  /**
   * Email address of the user.
   */
  email?: string;

  /**
   * Phone number of the user.
   */
  phoneNumber?: string;

  /**
   * Avatar URL of the user.
   */
  avatarUrl?: string;

  /**
   * HMAC-SHA256 signature generated by server using channel hmacSecret.
   */
  identifierHash?: string;

  /**
   * Additional custom key-value pairs.
   */
  customAttributes?: Record<string, unknown>;
}

/**
 * Public channel configuration returned by GET /api/v1/widget/config
 */
export interface WidgetConfigResponse {
  channelId: string;
  inboxId: string;
  widgetColor?: string;
  welcomeTitle?: string;
  welcomeTagline?: string;
  greetingMessage?: string;
  replyTime?: string;
  preChatFormEnabled?: boolean;
  preChatFormOptions?: {
    requireEmail?: boolean;
    requireName?: boolean;
    requirePhone?: boolean;
  };
  allowedDomains?: string;
  [key: string]: unknown;
}

/**
 * Session data returned by POST /api/v1/widget/contact
 */
export interface WidgetContactResponse {
  token: string;
  contactToken: string;
  contact: {
    id: string;
    name?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    avatarUrl?: string | null;
    identifier?: string | null;
    [key: string]: unknown;
  };
  isNewContact: boolean;
}

/**
 * Attachment structure in widget messages.
 */
export interface WidgetAttachment {
  id?: string;
  fileUrl: string;
  fileName?: string;
  fileType?: 'IMAGE' | 'AUDIO' | 'VIDEO' | 'FILE';
  fileSize?: number;
  contentType?: string;
}

/**
 * Normalized message format inside the widget SDK.
 */
export interface WidgetMessage {
  id: string;
  conversationId?: string;
  content: string | null;
  messageType: 'INCOMING' | 'OUTGOING' | 'SYSTEM';
  contentType: 'TEXT' | 'IMAGE' | 'AUDIO' | 'VIDEO' | 'FILE';
  senderType: 'CONTACT' | 'USER' | 'SYSTEM' | 'BOT';
  sender?: {
    id: string;
    name?: string | null;
    avatarUrl?: string | null;
  };
  attachments?: WidgetAttachment[];
  createdAt: string | Date;
  status?: 'SENDING' | 'SENT' | 'DELIVERED' | 'FAILED';
  tempId?: string;
}

/**
 * Widget SDK event listener callback.
 */
export type WidgetEventListener<T = unknown> = (data: T) => void;

/**
 * Map of SDK event types to their event payload.
 */
export interface WidgetEventMap {
  ready: void;
  open: void;
  close: void;
  toggle: { isOpen: boolean };
  'message:received': WidgetMessage;
  'message:sent': WidgetMessage;
  'typing:start': { sender: string };
  'typing:stop': { sender: string };
  identified: UserIdentity;
  error: { code: string; message: string; originalError?: unknown };
}
